@hostname = http://localhost:4000/api/v1
#@hostname = https://demo-smatera.bellyeah.jp/api/v1
@endpoint = /blogs
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAwMzY3NjI3LCJleHAiOjE3MDA0NTQwMjd9.I8vfUZzQC89Yu0BmCz6JSV34iACw6Sx-HyofntSveHI

### GET ALL RESOURCE
GET {{hostname}}{{endpoint}}
content-type: application/json
Authorization: {{token}}

### GET RESOURCE WITH FILTERS AND PAGINATION
GET {{hostname}}{{endpoint}}?sort=-title&sort=subtitle&page=1&limit=10
content-type: application/json
Authorization: {{token}}

### GET SINGLE RESOURCE
GET {{hostname}}{{endpoint}}/7
content-type: application/json
Authorization: {{token}}

### ADD/STORE RESOURCE
POST {{hostname}}{{endpoint}}
content-type: application/json
Authorization: {{token}}

{
   "title": "First Hero"
}

### UPDATE RESOURCE
PATCH {{hostname}}{{endpoint}}/1
content-type: application/json
Authorization: {{token}}

{
   "title": "First Hero Updated",
   "images": [1,2,3]
}

###
PATCH {{hostname}}{{endpoint}}/7                   
content-type: application/json
Authorization: {{token}}

{
  "first_name": "eugene"
}

### DELETE RESOURCE
DELETE {{hostname}}{{endpoint}}/6401f24b3c3d5cb4e6303ff0
content-type: application/json
Authorization: {{token}}