@hostname = http://localhost:4000/api/v1
#@hostname = https://demo-smatera.bellyeah.jp/api/v1
@endpoint = /blogs
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk5Nzk3MzQ4LCJleHAiOjE2OTk4ODM3NDh9.1Pf-gio2x7C1-O5tiVHEQ4BSNj4Zj2uP7c9M04U2Ajs

### GET ALL RESOURCE
GET {{hostname}}{{endpoint}}
content-type: application/json
Authorization: {{token}}

### GET RESOURCE WITH FILTERS AND PAGINATION
GET {{hostname}}{{endpoint}}?page=1&limit=10
content-type: application/json
Authorization: {{token}}

### GET SINGLE RESOURCE
GET {{hostname}}{{endpoint}}/7
content-type: application/json
Authorization: {{token}}

### ADD/STORE RESOURCE
POST {{hostname}}{{endpoint}}
content-type: application/json
Authorization: {{token}}

{
   "title": "First Hero"
}

### UPDATE RESOURCE
PATCH {{hostname}}{{endpoint}}/1
content-type: application/json
Authorization: {{token}}

{
   "title": "First Hero Updated",
   "images": [1,2,3]
}

###
PATCH {{hostname}}{{endpoint}}/7                   
content-type: application/json
Authorization: {{token}}

{
  "first_name": "eugene"
}

### DELETE RESOURCE
DELETE {{hostname}}{{endpoint}}/6401f24b3c3d5cb4e6303ff0
content-type: application/json
Authorization: {{token}}