@hostname = http://localhost:4000/api/v1
#@hostname = https://demo-smatera.bellyeah.jp/api/v1
@endpoint = /government_partners
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjk2ODU0NTMxLCJleHAiOjE2OTY5NDA5MzF9.vh9GJxG2yFeRSWsDQLmuyUMtUuR9P0dkh4Il6xj24No

### GET ALL RESOURCE
GET {{hostname}}{{endpoint}}
content-type: application/json
Authorization: {{token}}

### GET RESOURCE WITH FILTERS AND PAGINATION
GET {{hostname}}{{endpoint}}?page=1&limit=10
content-type: application/json
Authorization: {{token}}

### GET SINGLE RESOURCE
GET {{hostname}}{{endpoint}}/7
content-type: application/json
Authorization: {{token}}

### ADD/STORE RESOURCE
POST {{hostname}}{{endpoint}}
content-type: application/json
Authorization: {{token}}

{
   "title": "GOV_5",
   "images": [1,2,3]
}

### UPDATE RESOURCE
PATCH {{hostname}}{{endpoint}}/7
content-type: application/json
Authorization: {{token}}

{
   "title": "GOV_UPDATED_3",
   "images": [1,2,3]
}

###
PATCH {{hostname}}{{endpoint}}/7                   
content-type: application/json
Authorization: {{token}}

{
  "first_name": "eugene"
}

### DELETE RESOURCE
DELETE {{hostname}}{{endpoint}}/6401f24b3c3d5cb4e6303ff0
content-type: application/json
Authorization: {{token}}