#@hostname = http://localhost:4000/api/v1
@hostname = https://pami-dev.onrender.com/api/v1
@endpoint = /lu_ctpl
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzAyMDUwNDAyLCJleHAiOjE3MDIxMzY4MDJ9.V7aItlDSJaCWE0PzCZRlidd5oJWFH3BpEJ5NOffJqeU

### GET ALL RESOURCE
GET {{hostname}}{{endpoint}}
content-type: application/json
Authorization: {{token}}

### GET RESOURCE WITH FILTERS AND PAGINATION
GET {{hostname}}{{endpoint}}?page=1&limit=10
content-type: application/json
Authorization: {{token}}

### GET SINGLE RESOURCE
GET {{hostname}}{{endpoint}}/7
content-type: application/json
Authorization: {{token}}

### ADD/STORE RESOURCE
POST {{hostname}}{{endpoint}}
content-type: application/json
Authorization: {{token}}

{
  "COC_DATE": "11/20/2017",
    "TPLNUM": "CAR064956",
    "COC_CTRC": "CAR024523-SEDN032017",
    "LTF_CASE": "200001609",
    "LTF_OPER": "QUITENG, MARY",
    "LTF_ADDR": "2 PUROK 6 PINSAO PILOT PROJECT, BAGUIO CITY",
    "COC_PEFR": "11/20/2017",
    "COC_PETO": "11/20/2018",
    "VEH_MOYR": 2013,
    "VEH_MAKE": "ISUZU",
    "VEH_PLNO": "AYV143",
    "VEH_SENO": "PABTBR54FD2073195",
    "VEH_MONO": "4JA1M40651",
    "AGN_CODE": "I006",
    "AUTH_NO": "VALID",
    "MVFILE_NO": "142000000028657",
    "COC_AMT": 100
}

### UPDATE RESOURCE
PATCH {{hostname}}{{endpoint}}/1
content-type: application/json
Authorization: {{token}}

{
   "title": "First Hero Updated",
   "images": [1,2,3]
}

###
PATCH {{hostname}}{{endpoint}}/7                   
content-type: application/json
Authorization: {{token}}

{
  "first_name": "eugene"
}

### DELETE RESOURCE
DELETE {{hostname}}{{endpoint}}/6401f24b3c3d5cb4e6303ff0
content-type: application/json
Authorization: {{token}}

### Sample Data
[
  {
    "COC_DATE": "11/20/2017",
    "TPLNUM": "CAR063626",
    "COC_CTRC": "CAR024220-JEPN032017",
    "LTF_CASE": "2000011476",
    "LTF_OPER": "DUMLAO, IRENEO",
    "LTF_ADDR": "PALAQUIO, BUCAY, ABRA",
    "COC_PEFR": "11/20/2017",
    "COC_PETO": "11/20/2018",
    "VEH_MOYR": 2000,
    "VEH_MAKE": "ISUZU",
    "VEH_PLNO": "AYG363",
    "VEH_SENO": "NKR58L-7110194",
    "VEH_MONO": "4BD1-136157",
    "AGN_CODE": "I006",
    "AUTH_NO": null,
    "MVFILE_NO": "131200000195469",
    "COC_AMT": "-"
  },
  {
    "COC_DATE": "11/13/2017",
    "TPLNUM": "CAR063682",
    "COC_CTRC": "CAR023499-TRL1112017",
    "LTF_CASE": "2012CAR339",
    "LTF_OPER": "BACOCO, REYNARDO",
    "LTF_ADDR": "MIRADOR HILL, BAGUIO CITY",
    "COC_PEFR": "11/13/2017",
    "COC_PETO": "11/13/2018",
    "VEH_MOYR": 2003,
    "VEH_MAKE": "MITSUBISHI",
    "VEH_PLNO": "AYR321",
    "VEH_SENO": "PAEVB5NS13B000249",
    "VEH_MONO": "4D56A-N3533",
    "AGN_CODE": "I002",
    "AUTH_NO": null,
    "MVFILE_NO": "134000000323846",
    "COC_AMT": "-"
  },
  {
    "COC_DATE": "11/24/2017",
    "TPLNUM": "CAR064037",
    "COC_CTRC": "CAR026191-SEDN112017",
    "LTF_CASE": "2001BC438",
    "LTF_OPER": "IGARTA, PEDRO",
    "LTF_ADDR": "53 UPPER EAST, PRK. 1, CAMP 7, BAGUIO CITY",
    "COC_PEFR": "11/24/2017",
    "COC_PETO": "11/24/2018",
    "VEH_MOYR": 2013,
    "VEH_MAKE": "NISSAN",
    "VEH_PLNO": "WDQ884",
    "VEH_SENO": "TVP4LEFE24A50554",
    "VEH_MONO": "TD27940130",
    "AGN_CODE": "I001",
    "AUTH_NO": "VALD",
    "MVFILE_NO": "130800000554092",
    "COC_AMT": "-"
  },
  {
    "COC_DATE": "11/20/2017",
    "TPLNUM": "CAR064119",
    "COC_CTRC": "CAR025654-TRKN042017",
    "LTF_CASE": "2014CAR796",
    "LTF_OPER": "MARIANO, ROGER",
    "LTF_ADDR": "TUEY, TUBLAY, BENGUET",
    "COC_PEFR": "11/20/2017",
    "COC_PETO": "11/20/2018",
    "VEH_MOYR": 1996,
    "VEH_MAKE": "ISUZU",
    "VEH_PLNO": "UHZ561",
    "VEH_SENO": "FRR12JA3600898",
    "VEH_MONO": "6BG1S10301",
    "AGN_CODE": "I006",
    "AUTH_NO": "51609",
    "MVFILE_NO": "131200000103440",
    "COC_AMT": "-"
  },
  {
    "COC_DATE": "11/20/2017",
    "TPLNUM": "CAR064956",
    "COC_CTRC": "CAR024523-SEDN032017",
    "LTF_CASE": "200001609",
    "LTF_OPER": "QUITENG, MARY",
    "LTF_ADDR": "2 PUROK 6 PINSAO PILOT PROJECT, BAGUIO CITY",
    "COC_PEFR": "11/20/2017",
    "COC_PETO": "11/20/2018",
    "VEH_MOYR": 2013,
    "VEH_MAKE": "ISUZU",
    "VEH_PLNO": "AYV143",
    "VEH_SENO": "PABTBR54FD2073195",
    "VEH_MONO": "4JA1M40651",
    "AGN_CODE": "I006",
    "AUTH_NO": null,
    "MVFILE_NO": "142000000028657",
    "COC_AMT": "-"
  }
]

