@hostname = http://localhost:4000/api/v1
#@hostname = https://demo-smatera.bellyeah.jp/api/v1
@endpoint = /lu_ppai
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzAwODkyMzIzLCJleHAiOjE3MDA5Nzg3MjN9.yYWN5MIU8S4H7Pz3jSE-HfZ0a1oyju9r0ECG37xt-ac

### GET ALL RESOURCE
GET {{hostname}}{{endpoint}}
content-type: application/json
Authorization: {{token}}

### GET RESOURCE WITH FILTERS AND PAGINATION
GET {{hostname}}{{endpoint}}?COC_DATE[between]=['2017-02-02','2017-11-14']&page=1&limit=10
content-type: application/json
Authorization: {{token}}

### GET SINGLE RESOURCE
GET {{hostname}}{{endpoint}}/7
content-type: application/json
Authorization: {{token}}

### ADD/STORE RESOURCE
POST {{hostname}}{{endpoint}}
content-type: application/json
Authorization: {{token}}

{
    "COC_DATE": "11/13/2017",
    "COC_CTRC": "CAR027719-TRKN112017",
    "LTF_CASE": "98BC334",
    "LTF_OPER": "ACONG, FELICIDAD",
    "LTF_ADDR": "32 DOMINICAN HILL, BAGUIO CITY",
    "LTF_ORIG": "BAGUIO CITY",
    "LTF_DEST": "TO ANY PT. IN CAR",
    "LTF_VIA": "()",
    "COC_PEFR": "11/13/2017",
    "COC_PETO": "11/13/2018",
    "VEH_MOYR": 2015,
    "VEH_MAKE": "MITSUBISHI",
    "VEH_PLNO": "ABN9917",
    "VEH_SENO": "PAEVB5MLFFB001860",
    "VEH_MONO": "4D56AAL9352",
    "MVFILE_NO": "140400000058146",
    "AUTH_NO": "VALID",
    "AGN_CODE": "I006",
    "COC_AMT": 0
  }



### UPDATE RESOURCE
PATCH {{hostname}}{{endpoint}}/1
content-type: application/json
Authorization: {{token}}

{
   "title": "First Hero Updated",
   "images": [1,2,3]
}

###
PATCH {{hostname}}{{endpoint}}/7                   
content-type: application/json
Authorization: {{token}}

{
  "first_name": "eugene"
}

### DELETE RESOURCE
DELETE {{hostname}}{{endpoint}}/6401f24b3c3d5cb4e6303ff0
content-type: application/json
Authorization: {{token}}


### Sample data
[
  {
    "COC_DATE": "11/13/2017",
    "COC_CTRC": "CAR023499-TRL1112017",
    "LTF_CASE": "2012CAR339",
    "LTF_OPER": "BACOCO, REYNARDO",
    "LTF_ADDR": "MIRADOR HILL, BAGUIO CITY",
    "LTF_ORIG": "BAGUIO CITY",
    "LTF_DEST": "TO ANY PT. IN CAR",
    "LTF_VIA": "()",
    "COC_PEFR": "11/13/2017",
    "COC_PETO": "11/13/2018",
    "VEH_MOYR": 2003,
    "VEH_MAKE": "MITSUBISHI",
    "VEH_PLNO": "AYR321",
    "VEH_SENO": "PAEVB5NS13B000249",
    "VEH_MONO": "4D56A-N3533",
    "MVFILE_NO": "134000000323846",
    "AUTH_NO": null,
    "AGN_CODE": "I002",
    "COC_AMT": 0
  },
  {
    "COC_DATE": "11/15/2017",
    "COC_CTRC": "CAR024087-JEPN112017",
    "LTF_CASE": "8801655",
    "LTF_OPER": "SALOG, LUIS",
    "LTF_ADDR": "30 FRANCISCO MAYO, AMBIONG BAGUIO CITY",
    "LTF_ORIG": "BAGUIO PLAZA",
    "LTF_DEST": "AURORA HILL",
    "LTF_VIA": "()",
    "COC_PEFR": "11/15/2017",
    "COC_PETO": "11/15/2018",
    "VEH_MOYR": "NA",
    "VEH_MAKE": "FUSO",
    "VEH_PLNO": "AVA523",
    "VEH_SENO": "LTC MK 15920",
    "VEH_MONO": "5148",
    "MVFILE_NO": "13280000019864A",
    "AUTH_NO": "VALID",
    "AGN_CODE": "I001",
    "COC_AMT": 0
  },
  {
    "COC_DATE": "11/20/2017",
    "COC_CTRC": "CAR024461-TRL1112017",
    "LTF_CASE": "2004BAGCAR2052",
    "LTF_OPER": "CALIMLIM, VICTOR",
    "LTF_ADDR": "26 M.ROXAS ST., BRGY TABORA, BAGUIO CITY",
    "LTF_ORIG": "BAGUIO PLAZA",
    "LTF_DEST": "TRANCOVILLE",
    "LTF_VIA": "()",
    "COC_PEFR": "11/20/2017",
    "COC_PETO": "11/20/2018",
    "VEH_MOYR": 1996,
    "VEH_MAKE": "KIA",
    "VEH_PLNO": "AYR214",
    "VEH_SENO": "CMKW56 00273",
    "VEH_MONO": "SC 800036",
    "MVFILE_NO": "014000000193866",
    "AUTH_NO": null,
    "AGN_CODE": "I006",
    "COC_AMT": 0
  },
  {
    "COC_DATE": "11/20/2017",
    "COC_CTRC": "CAR025022-TRL1112017",
    "LTF_CASE": "04BC040",
    "LTF_OPER": "DELA CRUZ, BERNARDO",
    "LTF_ADDR": "ALAPANG LA TRINIDAD BENGUET",
    "LTF_ORIG": "BAGUIO CITY",
    "LTF_DEST": "ANY PT. IN CAR",
    "LTF_VIA": "()",
    "COC_PEFR": "11/20/2017",
    "COC_PETO": "11/20/2018",
    "VEH_MOYR": "NA",
    "VEH_MAKE": "MITSUBISHI",
    "VEH_PLNO": "AYR442",
    "VEH_SENO": "PAEVB5NJ15B 006698",
    "VEH_MONO": "4D56A-P6862",
    "MVFILE_NO": "140400000027151",
    "AUTH_NO": null,
    "AGN_CODE": "I006",
    "COC_AMT": 0
  },
  {
    "COC_DATE": "11/13/2017",
    "COC_CTRC": "CAR027719-TRKN112017",
    "LTF_CASE": "98BC334",
    "LTF_OPER": "ACONG, FELICIDAD",
    "LTF_ADDR": "32 DOMINICAN HILL, BAGUIO CITY",
    "LTF_ORIG": "BAGUIO CITY",
    "LTF_DEST": "TO ANY PT. IN CAR",
    "LTF_VIA": "()",
    "COC_PEFR": "11/13/2017",
    "COC_PETO": "11/13/2018",
    "VEH_MOYR": 2015,
    "VEH_MAKE": "MITSUBISHI",
    "VEH_PLNO": "ABN9917",
    "VEH_SENO": "PAEVB5MLFFB001860",
    "VEH_MONO": "4D56AAL9352",
    "MVFILE_NO": "140400000058146",
    "AUTH_NO": null,
    "AGN_CODE": "I006",
    "COC_AMT": 0
  }
]

